//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Yaw control mode
type VKFLY_YAW_CTRL_MODE uint64

const (
	// Yaw do not change. Keep current yaw.
	VKFLY_YAW_KEEP_CURRENT VKFLY_YAW_CTRL_MODE = 0
	// Yaw towards next waypoint or circle center.
	VKFLY_YAW_TO_NEXT_WP VKFLY_YAW_CTRL_MODE = 1
	// Yaw towards moving course heading.
	VKFLY_YAW_TO_TRACE_COURSE VKFLY_YAW_CTRL_MODE = 2
	// Yaw towards spacific value.
	VKFLY_YAW_TO_SET_VALUE VKFLY_YAW_CTRL_MODE = 3
	// Yaw towards home point.
	VKFLY_YAW_TO_HOME VKFLY_YAW_CTRL_MODE = 4
	// Yaw towards interest point.
	VKFLY_YAW_TO_INTEREST VKFLY_YAW_CTRL_MODE = 5
	// Yaw towards interest point.
	VKFLY_YAW_TO_OTHER_MAV_SYS VKFLY_YAW_CTRL_MODE = 6
	// Yaw towards interest point.
	VKFLY_YAW_TO_SET_VALUE_ONLY_ON_LANDING VKFLY_YAW_CTRL_MODE = 7
)

var value_to_label_VKFLY_YAW_CTRL_MODE = map[VKFLY_YAW_CTRL_MODE]string{
	VKFLY_YAW_KEEP_CURRENT: "VKFLY_YAW_KEEP_CURRENT",
	VKFLY_YAW_TO_NEXT_WP: "VKFLY_YAW_TO_NEXT_WP",
	VKFLY_YAW_TO_TRACE_COURSE: "VKFLY_YAW_TO_TRACE_COURSE",
	VKFLY_YAW_TO_SET_VALUE: "VKFLY_YAW_TO_SET_VALUE",
	VKFLY_YAW_TO_HOME: "VKFLY_YAW_TO_HOME",
	VKFLY_YAW_TO_INTEREST: "VKFLY_YAW_TO_INTEREST",
	VKFLY_YAW_TO_OTHER_MAV_SYS: "VKFLY_YAW_TO_OTHER_MAV_SYS",
	VKFLY_YAW_TO_SET_VALUE_ONLY_ON_LANDING: "VKFLY_YAW_TO_SET_VALUE_ONLY_ON_LANDING",
}

var label_to_value_VKFLY_YAW_CTRL_MODE = map[string]VKFLY_YAW_CTRL_MODE{
	"VKFLY_YAW_KEEP_CURRENT": VKFLY_YAW_KEEP_CURRENT,
	"VKFLY_YAW_TO_NEXT_WP": VKFLY_YAW_TO_NEXT_WP,
	"VKFLY_YAW_TO_TRACE_COURSE": VKFLY_YAW_TO_TRACE_COURSE,
	"VKFLY_YAW_TO_SET_VALUE": VKFLY_YAW_TO_SET_VALUE,
	"VKFLY_YAW_TO_HOME": VKFLY_YAW_TO_HOME,
	"VKFLY_YAW_TO_INTEREST": VKFLY_YAW_TO_INTEREST,
	"VKFLY_YAW_TO_OTHER_MAV_SYS": VKFLY_YAW_TO_OTHER_MAV_SYS,
	"VKFLY_YAW_TO_SET_VALUE_ONLY_ON_LANDING": VKFLY_YAW_TO_SET_VALUE_ONLY_ON_LANDING,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_YAW_CTRL_MODE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_YAW_CTRL_MODE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_YAW_CTRL_MODE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_YAW_CTRL_MODE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_YAW_CTRL_MODE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_YAW_CTRL_MODE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
