//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"strings"
	"fmt"
)
// Bitmap for ROI state
type VKFLY_ROI_STATE uint64

const (
	// Do nothing
	VKFLY_ROI_GIMBAL VKFLY_ROI_STATE = 1
	// Do nothing
	VKFLY_ROI_DRONE_HEAD VKFLY_ROI_STATE = 2
)
var values_VKFLY_ROI_STATE = []VKFLY_ROI_STATE{
	VKFLY_ROI_GIMBAL,
	VKFLY_ROI_DRONE_HEAD,
}

var value_to_label_VKFLY_ROI_STATE = map[VKFLY_ROI_STATE]string{
	VKFLY_ROI_GIMBAL: "VKFLY_ROI_GIMBAL",
	VKFLY_ROI_DRONE_HEAD: "VKFLY_ROI_DRONE_HEAD",
}

var label_to_value_VKFLY_ROI_STATE = map[string]VKFLY_ROI_STATE{
	"VKFLY_ROI_GIMBAL": VKFLY_ROI_GIMBAL,
	"VKFLY_ROI_DRONE_HEAD": VKFLY_ROI_DRONE_HEAD,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_ROI_STATE) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_VKFLY_ROI_STATE {
		if e&val == val {
			names = append(names, value_to_label_VKFLY_ROI_STATE[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_ROI_STATE) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask VKFLY_ROI_STATE
	for _, label := range labels {
		if value, ok := label_to_value_VKFLY_ROI_STATE[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= VKFLY_ROI_STATE(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_ROI_STATE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
