//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Failsafe action
type VKFLY_FS_ACTION uint64

const (
	// Do nothing
	FAIL_SAFE_ACT_NONE VKFLY_FS_ACTION = 0
	// Hold position for rotor wing. Loiter for fixedwing.
	FAIL_SAFE_ACT_LOITER VKFLY_FS_ACTION = 1
	// Return to lauch.
	FAIL_SAFE_ACT_RTL VKFLY_FS_ACTION = 2
	// Go to the nearest rally point.
	FAIL_SAFE_ACT_RTR VKFLY_FS_ACTION = 3
	// Landing in place.
	FAIL_SAFE_ACT_LAND VKFLY_FS_ACTION = 4
	// Terminate servo output and disarm the drone.
	FAIL_SAFE_ACT_LOCK VKFLY_FS_ACTION = 5
)

var value_to_label_VKFLY_FS_ACTION = map[VKFLY_FS_ACTION]string{
	FAIL_SAFE_ACT_NONE: "FAIL_SAFE_ACT_NONE",
	FAIL_SAFE_ACT_LOITER: "FAIL_SAFE_ACT_LOITER",
	FAIL_SAFE_ACT_RTL: "FAIL_SAFE_ACT_RTL",
	FAIL_SAFE_ACT_RTR: "FAIL_SAFE_ACT_RTR",
	FAIL_SAFE_ACT_LAND: "FAIL_SAFE_ACT_LAND",
	FAIL_SAFE_ACT_LOCK: "FAIL_SAFE_ACT_LOCK",
}

var label_to_value_VKFLY_FS_ACTION = map[string]VKFLY_FS_ACTION{
	"FAIL_SAFE_ACT_NONE": FAIL_SAFE_ACT_NONE,
	"FAIL_SAFE_ACT_LOITER": FAIL_SAFE_ACT_LOITER,
	"FAIL_SAFE_ACT_RTL": FAIL_SAFE_ACT_RTL,
	"FAIL_SAFE_ACT_RTR": FAIL_SAFE_ACT_RTR,
	"FAIL_SAFE_ACT_LAND": FAIL_SAFE_ACT_LAND,
	"FAIL_SAFE_ACT_LOCK": FAIL_SAFE_ACT_LOCK,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_FS_ACTION) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_FS_ACTION[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_FS_ACTION) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_FS_ACTION[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_FS_ACTION(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_FS_ACTION) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
