//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Gimbal action trigger on waypoint arrive.
type VKFLY_GIMBAL_WP_ACT uint64

const (
	// Do nothing.
	VKFLY_GIMBAL_WP_ACT_NONE VKFLY_GIMBAL_WP_ACT = 0
	// Do set gimbal pitch and yaw angle value.
	VKFLY_GIMBAL_WP_ACT_SET_ANG VKFLY_GIMBAL_WP_ACT = 1
	// Do set gimbla pitch value, yaw follow drone head.
	VKFLY_GIMBAL_WP_ACT_SET_PITCH_YAW_FOLLOW VKFLY_GIMBAL_WP_ACT = 2
	// Do set gimbla Zoom.
	VKFLY_GIMBAL_WP_SET_ZOOM VKFLY_GIMBAL_WP_ACT = 3
)

var value_to_label_VKFLY_GIMBAL_WP_ACT = map[VKFLY_GIMBAL_WP_ACT]string{
	VKFLY_GIMBAL_WP_ACT_NONE: "VKFLY_GIMBAL_WP_ACT_NONE",
	VKFLY_GIMBAL_WP_ACT_SET_ANG: "VKFLY_GIMBAL_WP_ACT_SET_ANG",
	VKFLY_GIMBAL_WP_ACT_SET_PITCH_YAW_FOLLOW: "VKFLY_GIMBAL_WP_ACT_SET_PITCH_YAW_FOLLOW",
	VKFLY_GIMBAL_WP_SET_ZOOM: "VKFLY_GIMBAL_WP_SET_ZOOM",
}

var label_to_value_VKFLY_GIMBAL_WP_ACT = map[string]VKFLY_GIMBAL_WP_ACT{
	"VKFLY_GIMBAL_WP_ACT_NONE": VKFLY_GIMBAL_WP_ACT_NONE,
	"VKFLY_GIMBAL_WP_ACT_SET_ANG": VKFLY_GIMBAL_WP_ACT_SET_ANG,
	"VKFLY_GIMBAL_WP_ACT_SET_PITCH_YAW_FOLLOW": VKFLY_GIMBAL_WP_ACT_SET_PITCH_YAW_FOLLOW,
	"VKFLY_GIMBAL_WP_SET_ZOOM": VKFLY_GIMBAL_WP_SET_ZOOM,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_GIMBAL_WP_ACT) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_GIMBAL_WP_ACT[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_GIMBAL_WP_ACT) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_GIMBAL_WP_ACT[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_GIMBAL_WP_ACT(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_GIMBAL_WP_ACT) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
