//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"strings"
	"fmt"
)
// For SYS_STATUS sensor extend flag use.
type VKFLY_SYS_STATUS_SENSOR_EXTEND uint64

const (
	// GPS2
	VKFLY_SYS_STATUS_SENSOR_GPS2 VKFLY_SYS_STATUS_SENSOR_EXTEND = 4
	// RTK GPS
	VKFLY_SYS_STATUS_SENSOR_RTK_GPS VKFLY_SYS_STATUS_SENSOR_EXTEND = 8
	// Onboard SD card
	VKFLY_SYS_STATUS_SDCARD VKFLY_SYS_STATUS_SENSOR_EXTEND = 16
)
var values_VKFLY_SYS_STATUS_SENSOR_EXTEND = []VKFLY_SYS_STATUS_SENSOR_EXTEND{
	VKFLY_SYS_STATUS_SENSOR_GPS2,
	VKFLY_SYS_STATUS_SENSOR_RTK_GPS,
	VKFLY_SYS_STATUS_SDCARD,
}

var value_to_label_VKFLY_SYS_STATUS_SENSOR_EXTEND = map[VKFLY_SYS_STATUS_SENSOR_EXTEND]string{
	VKFLY_SYS_STATUS_SENSOR_GPS2: "VKFLY_SYS_STATUS_SENSOR_GPS2",
	VKFLY_SYS_STATUS_SENSOR_RTK_GPS: "VKFLY_SYS_STATUS_SENSOR_RTK_GPS",
	VKFLY_SYS_STATUS_SDCARD: "VKFLY_SYS_STATUS_SDCARD",
}

var label_to_value_VKFLY_SYS_STATUS_SENSOR_EXTEND = map[string]VKFLY_SYS_STATUS_SENSOR_EXTEND{
	"VKFLY_SYS_STATUS_SENSOR_GPS2": VKFLY_SYS_STATUS_SENSOR_GPS2,
	"VKFLY_SYS_STATUS_SENSOR_RTK_GPS": VKFLY_SYS_STATUS_SENSOR_RTK_GPS,
	"VKFLY_SYS_STATUS_SDCARD": VKFLY_SYS_STATUS_SDCARD,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_SYS_STATUS_SENSOR_EXTEND) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_VKFLY_SYS_STATUS_SENSOR_EXTEND {
		if e&val == val {
			names = append(names, value_to_label_VKFLY_SYS_STATUS_SENSOR_EXTEND[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_SYS_STATUS_SENSOR_EXTEND) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask VKFLY_SYS_STATUS_SENSOR_EXTEND
	for _, label := range labels {
		if value, ok := label_to_value_VKFLY_SYS_STATUS_SENSOR_EXTEND[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= VKFLY_SYS_STATUS_SENSOR_EXTEND(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_SYS_STATUS_SENSOR_EXTEND) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
