//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// VKins magcalib stage
type VKFLY_MAGCALIB_STAGE uint64

const (
	// Not in calibration.
	VK_MAGCALIB_NONE VKFLY_MAGCALIB_STAGE = 0
	// Calibrating X-Y level.
	VK_MAGCALIB_XY VKFLY_MAGCALIB_STAGE = 1
	// Calibrating X-Z level.
	VK_MAGCALIB_XZ VKFLY_MAGCALIB_STAGE = 2
	// Calibrating successfully done.
	VK_MAGCALIB_DONE VKFLY_MAGCALIB_STAGE = 3
	// Calibrating failed.
	VK_MAGCALIB_FAIL VKFLY_MAGCALIB_STAGE = 4
)

var value_to_label_VKFLY_MAGCALIB_STAGE = map[VKFLY_MAGCALIB_STAGE]string{
	VK_MAGCALIB_NONE: "VK_MAGCALIB_NONE",
	VK_MAGCALIB_XY: "VK_MAGCALIB_XY",
	VK_MAGCALIB_XZ: "VK_MAGCALIB_XZ",
	VK_MAGCALIB_DONE: "VK_MAGCALIB_DONE",
	VK_MAGCALIB_FAIL: "VK_MAGCALIB_FAIL",
}

var label_to_value_VKFLY_MAGCALIB_STAGE = map[string]VKFLY_MAGCALIB_STAGE{
	"VK_MAGCALIB_NONE": VK_MAGCALIB_NONE,
	"VK_MAGCALIB_XY": VK_MAGCALIB_XY,
	"VK_MAGCALIB_XZ": VK_MAGCALIB_XZ,
	"VK_MAGCALIB_DONE": VK_MAGCALIB_DONE,
	"VK_MAGCALIB_FAIL": VK_MAGCALIB_FAIL,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_MAGCALIB_STAGE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_MAGCALIB_STAGE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_MAGCALIB_STAGE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_MAGCALIB_STAGE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_MAGCALIB_STAGE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_MAGCALIB_STAGE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
