//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Drone airframe
type VKFLY_AP_TYPE uint64

const (
	// Quadrotor I4
	VKFLY_AP_TYPE_I4 VKFLY_AP_TYPE = 41
	// Quadrotor X4
	VKFLY_AP_TYPE_X4 VKFLY_AP_TYPE = 42
	// Quadrotor X4 reverse
	VKFLY_AP_TYPE_X4R VKFLY_AP_TYPE = 43
	// Quadrotor I4 reverse
	VKFLY_AP_TYPE_I4R VKFLY_AP_TYPE = 44
	// Hexarotor I6
	VKFLY_AP_TYPE_I6 VKFLY_AP_TYPE = 61
	// Hexarotor X6
	VKFLY_AP_TYPE_X6 VKFLY_AP_TYPE = 62
	// Three axis hexarotor YI6D
	VKFLY_AP_TYPE_YI6D VKFLY_AP_TYPE = 63
	// Three axis hexarotor Y6D
	VKFLY_AP_TYPE_Y6D VKFLY_AP_TYPE = 64
	// Hexarotor H6
	VKFLY_AP_TYPE_H6 VKFLY_AP_TYPE = 65
	// Hexarotor I6 reverse
	VKFLY_AP_TYPE_I6R VKFLY_AP_TYPE = 66
	// Hexarotor X6 reverse
	VKFLY_AP_TYPE_X6R VKFLY_AP_TYPE = 67
	// Octorotor I8
	VKFLY_AP_TYPE_I8 VKFLY_AP_TYPE = 81
	// Octorotor X8
	VKFLY_AP_TYPE_X8 VKFLY_AP_TYPE = 82
	// Four axis octorotor, upper level X4, lower level reversed X4.
	VKFLY_AP_TYPE_4X8M VKFLY_AP_TYPE = 83
	// Four axis octorotor, upper level clockwise, lower level anticlockwise
	VKFLY_AP_TYPE_4X8D VKFLY_AP_TYPE = 84
	// Four axis octorotor, all rotors are opposite of 4X8M.
	VKFLY_AP_TYPE_4X8MR VKFLY_AP_TYPE = 85
	// Four axis octorotor, all rotors are opposite of 4X8M.
	VKFLY_AP_TYPE_4X8DR VKFLY_AP_TYPE = 86
	// Octorotor I8 reverse
	VKFLY_AP_TYPE_I8R VKFLY_AP_TYPE = 87
	// Octorotor X8 reverse
	VKFLY_AP_TYPE_X8R VKFLY_AP_TYPE = 88
	// Six axis twelve rotor, upper level I6, lower lever opposite with I6.
	VKFLY_AP_TYPE_6I12 VKFLY_AP_TYPE = 121
	// Six axis twelve rotor, upper level X6, lower lever opposite with X6.
	VKFLY_AP_TYPE_6X12 VKFLY_AP_TYPE = 122
	// Six axis twelve rotor, upper level H6, lower lever opposite with H6.
	VKFLY_AP_TYPE_6H12 VKFLY_AP_TYPE = 123
	// 8 axis 16 rotor, upper level I8, lower lever opposite with I8
	VKFLY_AP_TYPE_8I16 VKFLY_AP_TYPE = 161
	// 8 axis 16 rotor, upper level X8, lower lever opposite with X8
	VKFLY_AP_TYPE_8X16 VKFLY_AP_TYPE = 162
)

var value_to_label_VKFLY_AP_TYPE = map[VKFLY_AP_TYPE]string{
	VKFLY_AP_TYPE_I4: "VKFLY_AP_TYPE_I4",
	VKFLY_AP_TYPE_X4: "VKFLY_AP_TYPE_X4",
	VKFLY_AP_TYPE_X4R: "VKFLY_AP_TYPE_X4R",
	VKFLY_AP_TYPE_I4R: "VKFLY_AP_TYPE_I4R",
	VKFLY_AP_TYPE_I6: "VKFLY_AP_TYPE_I6",
	VKFLY_AP_TYPE_X6: "VKFLY_AP_TYPE_X6",
	VKFLY_AP_TYPE_YI6D: "VKFLY_AP_TYPE_YI6D",
	VKFLY_AP_TYPE_Y6D: "VKFLY_AP_TYPE_Y6D",
	VKFLY_AP_TYPE_H6: "VKFLY_AP_TYPE_H6",
	VKFLY_AP_TYPE_I6R: "VKFLY_AP_TYPE_I6R",
	VKFLY_AP_TYPE_X6R: "VKFLY_AP_TYPE_X6R",
	VKFLY_AP_TYPE_I8: "VKFLY_AP_TYPE_I8",
	VKFLY_AP_TYPE_X8: "VKFLY_AP_TYPE_X8",
	VKFLY_AP_TYPE_4X8M: "VKFLY_AP_TYPE_4X8M",
	VKFLY_AP_TYPE_4X8D: "VKFLY_AP_TYPE_4X8D",
	VKFLY_AP_TYPE_4X8MR: "VKFLY_AP_TYPE_4X8MR",
	VKFLY_AP_TYPE_4X8DR: "VKFLY_AP_TYPE_4X8DR",
	VKFLY_AP_TYPE_I8R: "VKFLY_AP_TYPE_I8R",
	VKFLY_AP_TYPE_X8R: "VKFLY_AP_TYPE_X8R",
	VKFLY_AP_TYPE_6I12: "VKFLY_AP_TYPE_6I12",
	VKFLY_AP_TYPE_6X12: "VKFLY_AP_TYPE_6X12",
	VKFLY_AP_TYPE_6H12: "VKFLY_AP_TYPE_6H12",
	VKFLY_AP_TYPE_8I16: "VKFLY_AP_TYPE_8I16",
	VKFLY_AP_TYPE_8X16: "VKFLY_AP_TYPE_8X16",
}

var label_to_value_VKFLY_AP_TYPE = map[string]VKFLY_AP_TYPE{
	"VKFLY_AP_TYPE_I4": VKFLY_AP_TYPE_I4,
	"VKFLY_AP_TYPE_X4": VKFLY_AP_TYPE_X4,
	"VKFLY_AP_TYPE_X4R": VKFLY_AP_TYPE_X4R,
	"VKFLY_AP_TYPE_I4R": VKFLY_AP_TYPE_I4R,
	"VKFLY_AP_TYPE_I6": VKFLY_AP_TYPE_I6,
	"VKFLY_AP_TYPE_X6": VKFLY_AP_TYPE_X6,
	"VKFLY_AP_TYPE_YI6D": VKFLY_AP_TYPE_YI6D,
	"VKFLY_AP_TYPE_Y6D": VKFLY_AP_TYPE_Y6D,
	"VKFLY_AP_TYPE_H6": VKFLY_AP_TYPE_H6,
	"VKFLY_AP_TYPE_I6R": VKFLY_AP_TYPE_I6R,
	"VKFLY_AP_TYPE_X6R": VKFLY_AP_TYPE_X6R,
	"VKFLY_AP_TYPE_I8": VKFLY_AP_TYPE_I8,
	"VKFLY_AP_TYPE_X8": VKFLY_AP_TYPE_X8,
	"VKFLY_AP_TYPE_4X8M": VKFLY_AP_TYPE_4X8M,
	"VKFLY_AP_TYPE_4X8D": VKFLY_AP_TYPE_4X8D,
	"VKFLY_AP_TYPE_4X8MR": VKFLY_AP_TYPE_4X8MR,
	"VKFLY_AP_TYPE_4X8DR": VKFLY_AP_TYPE_4X8DR,
	"VKFLY_AP_TYPE_I8R": VKFLY_AP_TYPE_I8R,
	"VKFLY_AP_TYPE_X8R": VKFLY_AP_TYPE_X8R,
	"VKFLY_AP_TYPE_6I12": VKFLY_AP_TYPE_6I12,
	"VKFLY_AP_TYPE_6X12": VKFLY_AP_TYPE_6X12,
	"VKFLY_AP_TYPE_6H12": VKFLY_AP_TYPE_6H12,
	"VKFLY_AP_TYPE_8I16": VKFLY_AP_TYPE_8I16,
	"VKFLY_AP_TYPE_8X16": VKFLY_AP_TYPE_8X16,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_AP_TYPE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_AP_TYPE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_AP_TYPE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_AP_TYPE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_AP_TYPE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_AP_TYPE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
