//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
type VKFLY_FORMATION_TYPE uint64

const (
	VKFLY_FORMATION_ROW VKFLY_FORMATION_TYPE = 0
	VKFLY_FORMATION_COLUM VKFLY_FORMATION_TYPE = 1
	VKFLY_FORMATION_TRIANGLE VKFLY_FORMATION_TYPE = 2
	VKFLY_FORMATION_RECTANGLE VKFLY_FORMATION_TYPE = 3
	VKFLY_FORMATION_CUSTOM VKFLY_FORMATION_TYPE = 4
	VKFLY_FORMATION_VERTICLE_LINE VKFLY_FORMATION_TYPE = 5
)

var value_to_label_VKFLY_FORMATION_TYPE = map[VKFLY_FORMATION_TYPE]string{
	VKFLY_FORMATION_ROW: "VKFLY_FORMATION_ROW",
	VKFLY_FORMATION_COLUM: "VKFLY_FORMATION_COLUM",
	VKFLY_FORMATION_TRIANGLE: "VKFLY_FORMATION_TRIANGLE",
	VKFLY_FORMATION_RECTANGLE: "VKFLY_FORMATION_RECTANGLE",
	VKFLY_FORMATION_CUSTOM: "VKFLY_FORMATION_CUSTOM",
	VKFLY_FORMATION_VERTICLE_LINE: "VKFLY_FORMATION_VERTICLE_LINE",
}

var label_to_value_VKFLY_FORMATION_TYPE = map[string]VKFLY_FORMATION_TYPE{
	"VKFLY_FORMATION_ROW": VKFLY_FORMATION_ROW,
	"VKFLY_FORMATION_COLUM": VKFLY_FORMATION_COLUM,
	"VKFLY_FORMATION_TRIANGLE": VKFLY_FORMATION_TRIANGLE,
	"VKFLY_FORMATION_RECTANGLE": VKFLY_FORMATION_RECTANGLE,
	"VKFLY_FORMATION_CUSTOM": VKFLY_FORMATION_CUSTOM,
	"VKFLY_FORMATION_VERTICLE_LINE": VKFLY_FORMATION_VERTICLE_LINE,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_FORMATION_TYPE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_FORMATION_TYPE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_FORMATION_TYPE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_FORMATION_TYPE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_FORMATION_TYPE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_FORMATION_TYPE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
