//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"strings"
	"fmt"
)
// bitmap for VKins navigtion status
type VKFLY_VKINS_NAV_STATUS uint64

const (
	// INS status. 0 means no INS. 1 means INS ok.
	VKFLY_VKINS_NAV_INSGPS VKFLY_VKINS_NAV_STATUS = 1
	// GPS altitude in data fusion. 0 gps altitude not used. 1 gps altitude used.
	VKFLY_VKINS_NAV_ALT_GPS VKFLY_VKINS_NAV_STATUS = 2
	// RTK heading data. 0 use mag, 1 use rtk dual ant heading.
	VKFLY_VKINS_NAV_HEADING_RTK VKFLY_VKINS_NAV_STATUS = 4
	// RTK pos data. 0 no RTK, 1 RTK.
	VKFLY_VKINS_NAV_RTK VKFLY_VKINS_NAV_STATUS = 16
)
var values_VKFLY_VKINS_NAV_STATUS = []VKFLY_VKINS_NAV_STATUS{
	VKFLY_VKINS_NAV_INSGPS,
	VKFLY_VKINS_NAV_ALT_GPS,
	VKFLY_VKINS_NAV_HEADING_RTK,
	VKFLY_VKINS_NAV_RTK,
}

var value_to_label_VKFLY_VKINS_NAV_STATUS = map[VKFLY_VKINS_NAV_STATUS]string{
	VKFLY_VKINS_NAV_INSGPS: "VKFLY_VKINS_NAV_INSGPS",
	VKFLY_VKINS_NAV_ALT_GPS: "VKFLY_VKINS_NAV_ALT_GPS",
	VKFLY_VKINS_NAV_HEADING_RTK: "VKFLY_VKINS_NAV_HEADING_RTK",
	VKFLY_VKINS_NAV_RTK: "VKFLY_VKINS_NAV_RTK",
}

var label_to_value_VKFLY_VKINS_NAV_STATUS = map[string]VKFLY_VKINS_NAV_STATUS{
	"VKFLY_VKINS_NAV_INSGPS": VKFLY_VKINS_NAV_INSGPS,
	"VKFLY_VKINS_NAV_ALT_GPS": VKFLY_VKINS_NAV_ALT_GPS,
	"VKFLY_VKINS_NAV_HEADING_RTK": VKFLY_VKINS_NAV_HEADING_RTK,
	"VKFLY_VKINS_NAV_RTK": VKFLY_VKINS_NAV_RTK,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_VKINS_NAV_STATUS) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_VKFLY_VKINS_NAV_STATUS {
		if e&val == val {
			names = append(names, value_to_label_VKFLY_VKINS_NAV_STATUS[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_VKINS_NAV_STATUS) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask VKFLY_VKINS_NAV_STATUS
	for _, label := range labels {
		if value, ok := label_to_value_VKFLY_VKINS_NAV_STATUS[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= VKFLY_VKINS_NAV_STATUS(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_VKINS_NAV_STATUS) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
