//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Digicam action trigger on waypoint arrive.
type VKFLY_DIGICAM_WP_ACT uint64

const (
	// Do nothing.
	VKFLY_DIGICAM_WP_ACT_NONE VKFLY_DIGICAM_WP_ACT = 0
	// Do take photo.
	VKFLY_DIGICAM_WP_ACT_PHO VKFLY_DIGICAM_WP_ACT = 1
	// Do vedio recording on.
	VKFLY_DIGICAM_WP_ACT_VEDIO_ON VKFLY_DIGICAM_WP_ACT = 2
	// Do vedio recording off.
	VKFLY_DIGICAM_WP_ACT_VEDIO_OFF VKFLY_DIGICAM_WP_ACT = 3
)

var value_to_label_VKFLY_DIGICAM_WP_ACT = map[VKFLY_DIGICAM_WP_ACT]string{
	VKFLY_DIGICAM_WP_ACT_NONE: "VKFLY_DIGICAM_WP_ACT_NONE",
	VKFLY_DIGICAM_WP_ACT_PHO: "VKFLY_DIGICAM_WP_ACT_PHO",
	VKFLY_DIGICAM_WP_ACT_VEDIO_ON: "VKFLY_DIGICAM_WP_ACT_VEDIO_ON",
	VKFLY_DIGICAM_WP_ACT_VEDIO_OFF: "VKFLY_DIGICAM_WP_ACT_VEDIO_OFF",
}

var label_to_value_VKFLY_DIGICAM_WP_ACT = map[string]VKFLY_DIGICAM_WP_ACT{
	"VKFLY_DIGICAM_WP_ACT_NONE": VKFLY_DIGICAM_WP_ACT_NONE,
	"VKFLY_DIGICAM_WP_ACT_PHO": VKFLY_DIGICAM_WP_ACT_PHO,
	"VKFLY_DIGICAM_WP_ACT_VEDIO_ON": VKFLY_DIGICAM_WP_ACT_VEDIO_ON,
	"VKFLY_DIGICAM_WP_ACT_VEDIO_OFF": VKFLY_DIGICAM_WP_ACT_VEDIO_OFF,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_DIGICAM_WP_ACT) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_DIGICAM_WP_ACT[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_DIGICAM_WP_ACT) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_DIGICAM_WP_ACT[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_DIGICAM_WP_ACT(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_DIGICAM_WP_ACT) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
