//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
type VKFLY_RTL_EXEC_MODE uint64

const (
	VKFLY_RTL_EXEC_MODE_NORMAL VKFLY_RTL_EXEC_MODE = 0
	VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ VKFLY_RTL_EXEC_MODE = 1
	VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ_REVERSE VKFLY_RTL_EXEC_MODE = 2
)

var value_to_label_VKFLY_RTL_EXEC_MODE = map[VKFLY_RTL_EXEC_MODE]string{
	VKFLY_RTL_EXEC_MODE_NORMAL: "VKFLY_RTL_EXEC_MODE_NORMAL",
	VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ: "VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ",
	VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ_REVERSE: "VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ_REVERSE",
}

var label_to_value_VKFLY_RTL_EXEC_MODE = map[string]VKFLY_RTL_EXEC_MODE{
	"VKFLY_RTL_EXEC_MODE_NORMAL": VKFLY_RTL_EXEC_MODE_NORMAL,
	"VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ": VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ,
	"VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ_REVERSE": VKFLY_RTL_EXEC_MODE_BY_MISSION_SEQ_REVERSE,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_RTL_EXEC_MODE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_RTL_EXEC_MODE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_RTL_EXEC_MODE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_RTL_EXEC_MODE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_RTL_EXEC_MODE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_RTL_EXEC_MODE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
