//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"fmt"
)
// Digicam auto take photo mode.
type VKFLY_PHOTO_CTRL_MODE uint64

const (
	// Do not take photo automatically.
	VKFLY_AUTO_PHO_KEEP_CURRENT VKFLY_PHOTO_CTRL_MODE = 0
	// Do not take photo automatically.
	VKFLY_AUTO_PHO_STOP VKFLY_PHOTO_CTRL_MODE = 1
	// Automatically take photo by tiem.
	VKFLY_AUTO_PHO_AUTO_BY_TIME VKFLY_PHOTO_CTRL_MODE = 2
	// Automatically take photo by distance.
	VKFLY_AUTO_PHO_BY_DIST_XY VKFLY_PHOTO_CTRL_MODE = 3
	// Automatically take photo by input trigger signal or command.
	VKFLY_AUTO_PHO_BY_DIST_Z VKFLY_PHOTO_CTRL_MODE = 4
	// Automatically take photo by input trigger signal or command.
	VKFLY_AUTO_PHO_BY_DIST_XYZ VKFLY_PHOTO_CTRL_MODE = 5
)

var value_to_label_VKFLY_PHOTO_CTRL_MODE = map[VKFLY_PHOTO_CTRL_MODE]string{
	VKFLY_AUTO_PHO_KEEP_CURRENT: "VKFLY_AUTO_PHO_KEEP_CURRENT",
	VKFLY_AUTO_PHO_STOP: "VKFLY_AUTO_PHO_STOP",
	VKFLY_AUTO_PHO_AUTO_BY_TIME: "VKFLY_AUTO_PHO_AUTO_BY_TIME",
	VKFLY_AUTO_PHO_BY_DIST_XY: "VKFLY_AUTO_PHO_BY_DIST_XY",
	VKFLY_AUTO_PHO_BY_DIST_Z: "VKFLY_AUTO_PHO_BY_DIST_Z",
	VKFLY_AUTO_PHO_BY_DIST_XYZ: "VKFLY_AUTO_PHO_BY_DIST_XYZ",
}

var label_to_value_VKFLY_PHOTO_CTRL_MODE = map[string]VKFLY_PHOTO_CTRL_MODE{
	"VKFLY_AUTO_PHO_KEEP_CURRENT": VKFLY_AUTO_PHO_KEEP_CURRENT,
	"VKFLY_AUTO_PHO_STOP": VKFLY_AUTO_PHO_STOP,
	"VKFLY_AUTO_PHO_AUTO_BY_TIME": VKFLY_AUTO_PHO_AUTO_BY_TIME,
	"VKFLY_AUTO_PHO_BY_DIST_XY": VKFLY_AUTO_PHO_BY_DIST_XY,
	"VKFLY_AUTO_PHO_BY_DIST_Z": VKFLY_AUTO_PHO_BY_DIST_Z,
	"VKFLY_AUTO_PHO_BY_DIST_XYZ": VKFLY_AUTO_PHO_BY_DIST_XYZ,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_PHOTO_CTRL_MODE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_VKFLY_PHOTO_CTRL_MODE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_PHOTO_CTRL_MODE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_VKFLY_PHOTO_CTRL_MODE[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = VKFLY_PHOTO_CTRL_MODE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_PHOTO_CTRL_MODE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
