//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package vkfly

import (
	"strconv"
	"strings"
	"fmt"
)
// bitmap of throwing channel
type VKFLY_THROW_CHAN_TYPE uint64

const (
	// throwing channel1
	VKFLY_THROW_CHAN_1 VKFLY_THROW_CHAN_TYPE = 1
	// throwing channel2
	VKFLY_THROW_CHAN_2 VKFLY_THROW_CHAN_TYPE = 2
	// throwing channel3
	VKFLY_THROW_CHAN_3 VKFLY_THROW_CHAN_TYPE = 4
	// throwing channel4
	VKFLY_THROW_CHAN_4 VKFLY_THROW_CHAN_TYPE = 8
	// throwing channel5
	VKFLY_THROW_CHAN_5 VKFLY_THROW_CHAN_TYPE = 16
	// throwing channel6
	VKFLY_THROW_CHAN_6 VKFLY_THROW_CHAN_TYPE = 32
	// throwing channel7
	VKFLY_THROW_CHAN_7 VKFLY_THROW_CHAN_TYPE = 64
	// throwing channel8
	VKFLY_THROW_CHAN_8 VKFLY_THROW_CHAN_TYPE = 128
	// throwing channel9
	VKFLY_THROW_CHAN_9 VKFLY_THROW_CHAN_TYPE = 256
	// throwing channel10
	VKFLY_THROW_CHAN_10 VKFLY_THROW_CHAN_TYPE = 512
	// throwing channel11
	VKFLY_THROW_CHAN_11 VKFLY_THROW_CHAN_TYPE = 1024
	// throwing channel12
	VKFLY_THROW_CHAN_12 VKFLY_THROW_CHAN_TYPE = 2048
	// throwing channel12
	VKFLY_THROW_CHAN_13 VKFLY_THROW_CHAN_TYPE = 4096
	// throwing channel12
	VKFLY_THROW_CHAN_14 VKFLY_THROW_CHAN_TYPE = 8192
	// throwing channel12
	VKFLY_THROW_CHAN_15 VKFLY_THROW_CHAN_TYPE = 16384
	// throwing channel12
	VKFLY_THROW_CHAN_16 VKFLY_THROW_CHAN_TYPE = 32768
	// throwing channel12
	VKFLY_THROW_CHAN_ALL VKFLY_THROW_CHAN_TYPE = 65535
)
var values_VKFLY_THROW_CHAN_TYPE = []VKFLY_THROW_CHAN_TYPE{
	VKFLY_THROW_CHAN_1,
	VKFLY_THROW_CHAN_2,
	VKFLY_THROW_CHAN_3,
	VKFLY_THROW_CHAN_4,
	VKFLY_THROW_CHAN_5,
	VKFLY_THROW_CHAN_6,
	VKFLY_THROW_CHAN_7,
	VKFLY_THROW_CHAN_8,
	VKFLY_THROW_CHAN_9,
	VKFLY_THROW_CHAN_10,
	VKFLY_THROW_CHAN_11,
	VKFLY_THROW_CHAN_12,
	VKFLY_THROW_CHAN_13,
	VKFLY_THROW_CHAN_14,
	VKFLY_THROW_CHAN_15,
	VKFLY_THROW_CHAN_16,
	VKFLY_THROW_CHAN_ALL,
}

var value_to_label_VKFLY_THROW_CHAN_TYPE = map[VKFLY_THROW_CHAN_TYPE]string{
	VKFLY_THROW_CHAN_1: "VKFLY_THROW_CHAN_1",
	VKFLY_THROW_CHAN_2: "VKFLY_THROW_CHAN_2",
	VKFLY_THROW_CHAN_3: "VKFLY_THROW_CHAN_3",
	VKFLY_THROW_CHAN_4: "VKFLY_THROW_CHAN_4",
	VKFLY_THROW_CHAN_5: "VKFLY_THROW_CHAN_5",
	VKFLY_THROW_CHAN_6: "VKFLY_THROW_CHAN_6",
	VKFLY_THROW_CHAN_7: "VKFLY_THROW_CHAN_7",
	VKFLY_THROW_CHAN_8: "VKFLY_THROW_CHAN_8",
	VKFLY_THROW_CHAN_9: "VKFLY_THROW_CHAN_9",
	VKFLY_THROW_CHAN_10: "VKFLY_THROW_CHAN_10",
	VKFLY_THROW_CHAN_11: "VKFLY_THROW_CHAN_11",
	VKFLY_THROW_CHAN_12: "VKFLY_THROW_CHAN_12",
	VKFLY_THROW_CHAN_13: "VKFLY_THROW_CHAN_13",
	VKFLY_THROW_CHAN_14: "VKFLY_THROW_CHAN_14",
	VKFLY_THROW_CHAN_15: "VKFLY_THROW_CHAN_15",
	VKFLY_THROW_CHAN_16: "VKFLY_THROW_CHAN_16",
	VKFLY_THROW_CHAN_ALL: "VKFLY_THROW_CHAN_ALL",
}

var label_to_value_VKFLY_THROW_CHAN_TYPE = map[string]VKFLY_THROW_CHAN_TYPE{
	"VKFLY_THROW_CHAN_1": VKFLY_THROW_CHAN_1,
	"VKFLY_THROW_CHAN_2": VKFLY_THROW_CHAN_2,
	"VKFLY_THROW_CHAN_3": VKFLY_THROW_CHAN_3,
	"VKFLY_THROW_CHAN_4": VKFLY_THROW_CHAN_4,
	"VKFLY_THROW_CHAN_5": VKFLY_THROW_CHAN_5,
	"VKFLY_THROW_CHAN_6": VKFLY_THROW_CHAN_6,
	"VKFLY_THROW_CHAN_7": VKFLY_THROW_CHAN_7,
	"VKFLY_THROW_CHAN_8": VKFLY_THROW_CHAN_8,
	"VKFLY_THROW_CHAN_9": VKFLY_THROW_CHAN_9,
	"VKFLY_THROW_CHAN_10": VKFLY_THROW_CHAN_10,
	"VKFLY_THROW_CHAN_11": VKFLY_THROW_CHAN_11,
	"VKFLY_THROW_CHAN_12": VKFLY_THROW_CHAN_12,
	"VKFLY_THROW_CHAN_13": VKFLY_THROW_CHAN_13,
	"VKFLY_THROW_CHAN_14": VKFLY_THROW_CHAN_14,
	"VKFLY_THROW_CHAN_15": VKFLY_THROW_CHAN_15,
	"VKFLY_THROW_CHAN_16": VKFLY_THROW_CHAN_16,
	"VKFLY_THROW_CHAN_ALL": VKFLY_THROW_CHAN_ALL,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e VKFLY_THROW_CHAN_TYPE) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_VKFLY_THROW_CHAN_TYPE {
		if e&val == val {
			names = append(names, value_to_label_VKFLY_THROW_CHAN_TYPE[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *VKFLY_THROW_CHAN_TYPE) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask VKFLY_THROW_CHAN_TYPE
	for _, label := range labels {
		if value, ok := label_to_value_VKFLY_THROW_CHAN_TYPE[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= VKFLY_THROW_CHAN_TYPE(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e VKFLY_THROW_CHAN_TYPE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
