//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY transfer update terminate. Send this message to terminate a update file
// transfer.
type MessageVkUpdateTerminate struct {
	// Target system id.
	TargetSystem uint8
	// Target compid id.
	TargetComp uint8
}

// GetID implements the message.Message interface.
func (*MessageVkUpdateTerminate) GetID() uint32 {
	return 53104
}
