//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// engine ecu status message
type MessageVkEngineEcuStaus struct {
	// Timestamp in ms from system boot.
	Timestamp uint32
	// rotational speed in rpm
	SpdRpm uint16
	// throttle
	// position
	ThrPos uint8
	// fuel
	// position
	FuelPos uint8
	// CylinderA head temperature
	CylinderaTemp int16 `mavname:"cylinderA_temp"`
	// CylinderB head temperature
	CylinderbTemp int16 `mavname:"cylinderB_temp"`
	// coolant head temperature
	CoolantTemp int16
	// engine index
	FuelRemain uint16
	// range extender alarm bitmap
	Alarm uint16
	// range extender output voltage
	TotalRuntime uint32
	// range extender output voltage
	Runtime uint16
	// left time for service
	ServiceTime uint16
	// range extender output voltage
	OutputVolt uint16
	// range extender output current
	OutputCurr uint16
	// engine fault
	Fault uint8
	// engine state
	EngineState uint8
	// engine index
	Index uint8
	// engine state
	Reserve [4]uint8
	// inlet air pressure
	InletPressure uint16 `mavext:"true"`
	// Ge temperature
	GeTemp int16 `mavext:"true"`
	// air temperature
	AirTemp int16 `mavext:"true"`
	// temperature 1
	Temp_1 int16 `mavext:"true"`
	// volt 2
	Volt_2 int16 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageVkEngineEcuStaus) GetID() uint32 {
	return 53005
}
