//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VK external INS navigation
type MessageVkExternalInsNav struct {
	// timestamp from system boot
	Timestamp uint32
	// solved longitude
	Lon int32
	// solved latitude
	Lat int32
	// solved latitude
	Msl float32
	// solved east speed
	Ve float32
	// solved north speed
	Vn float32
	// solved up speed
	Vu float32
	// yaw angle
	Yaw float32
	// pitch angle
	Pitch float32
	// roll angle
	Roll float32
	// roll angle
	Gx float32
	// roll angle
	Gy float32
	// roll angle
	Gz float32
	// roll angle
	Ax float32
	// roll angle
	Ay float32
	// roll angle
	Az float32
	// gps longitude
	SatLon int32
	// gps latitude
	SatLat int32
	// gps altitude
	SatMsl float32
	// gps east speed
	SatVe float32
	// gps north speed
	SatVn float32
	// gps up speed
	SatVu float32
	// gps position fix
	SatPfix uint8
	// gps heading fix
	SatHfix uint8
	// work state
	WkState uint8
	// error code
	ErrCode uint8
}

// GetID implements the message.Message interface.
func (*MessageVkExternalInsNav) GetID() uint32 {
	return 53023
}
