//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Airspeed information from a sensor.
type MessageVkAirspeed struct {
	// Sensor ID.
	Id uint8
	// Calibrated airspeed (CAS).
	Airspeed float32
	// Temperature.
	Temperature int16
	// Raw differential pressure.
	RawPress float32
	// Airspeed sensor flags.
	Flags uint8
}

// GetID implements the message.Message interface.
func (*MessageVkAirspeed) GetID() uint32 {
	return 53012
}
