//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// EDU status ack
type MessageVkflyEduStatusAck struct {
	// Unix timestamp in ms, from 1 Jan 1970.
	UnixTimestamp uint64
	// Sequence number in the received VKFLY_EDU_STATUS.
	Seq uint32
}

// GetID implements the message.Message interface.
func (*MessageVkflyEduStatusAck) GetID() uint32 {
	return 53026
}
