//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
type MessageVkinsStatus struct {
	// Timestamp in ms from system boot.
	TimeBootMs uint32
	// VKINS
	// navigation status flag.
	NavStatus VKFLY_VKINS_NAV_STATUS `mavenum:"uint8"`
	// vinks flag1
	SFlag1 uint8
	// vinks flag2.
	SFlag2 uint8
	// vinks flag3.
	SFlag3 uint8
	// vinks flag4.
	SFlag4 uint8
	// vinks flag5.
	SFlag5 uint8
	// vinks flag6.
	SFlag6 uint8
	// vkins mag calib
	// stage.
	MagCalibStage VKFLY_MAGCALIB_STAGE `mavenum:"uint8"`
	// vkins initial calibrated gravitation acceleration.
	G0 float32
	// raw longitude for data fusion
	RawLatitude int32
	// raw latitidue for data fusion
	RawLongitude int32
	// raw baromoter altitude for data fusion
	BaroAlt float32
	// gps amsl altitude for data fusion
	RawGpsAlt float32
	// satelites number for position
	SolvPsatNum uint8
	// satelites number for heading
	SolvHsatNum uint8
	// temperature
	Temperature int16
	VibeCoe uint8
}

// GetID implements the message.Message interface.
func (*MessageVkinsStatus) GetID() uint32 {
	return 53000
}
