//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// formation fly leader status message
type MessageVkFormationLeader struct {
	// Timestamp in ms from system boot.
	Timestamp uint32
	// formation leader drone state bitmap
	State uint32
	// formation leader latitude in 1e-7deg
	Lat int32
	// formation leader longitude in 1e-7deg
	Lon int32
	// formation leader msl altitude in meter
	Msl float32
	// formation leader east speed
	Ve float32
	// formation leader north speed
	Vn float32
	// formation leader up speed
	Vu float32
	// formation leader yaw
	Yaw float32
	// formation type
	FormationType VKFLY_FORMATION_TYPE `mavenum:"uint8"`
	// distance between drones in x axis
	XDist int16
	// distance between drones in y axis
	YDist int16
	// distance between drones in z axis
	ZDist int16
	// columns number of rectangle formation
	RectColNum uint16
	// if nan, use yaw as formation heading
	FormationHeading float32 `mavext:"true"`
	// 0 unlock, 1 lock
	FormHeadLock float32 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageVkFormationLeader) GetID() uint32 {
	return 53004
}
