//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY transfer update file data.
type MessageVkFwUpdateData struct {
	// Offset into the update file.
	Offset uint32
	// Number of bytes.
	// Zero for end of file.
	Count uint8
	// File data.
	Data [128]uint8
}

// GetID implements the message.Message interface.
func (*MessageVkFwUpdateData) GetID() uint32 {
	return 53103
}
