//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Mosaic_h gps raw data
type MessageVkMosaichGpsRaw struct {
	// Timestamp (UNIX Epoch time or time since
	// system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system
	// boot) by checking for the magnitude of the number.
	TimeUsec uint64
	// GPS fix type.
	FixType GPS_FIX_TYPE `mavenum:"uint8"`
	// Number of satellites for positioning ANT
	PsvNum uint8
	// refer to mosaic_h reference page 308
	PvtErr uint8
	// refer to mosaic_h reference page 308
	PvtMode uint8
	// Latitude (WGS84, EGM96 ellipsoid)
	Lat int32
	// Longitude (WGS84, EGM96 ellipsoid)
	Lon int32
	// Altitude (Ellipsoild). Positive for up.
	EllipsoidAlt float32
	// Ease speed in m/s.
	Ve float32
	// North speed in m/s.
	Vn float32
	// Up speed in m/s.
	Vu float32
	// Position uncertainty.
	HAcc uint16
	// Altitude uncertainty.
	VAcc uint16
	// Attitude euler yaw.
	Yaw float32
	// Attitude euler pitch.
	Pitch float32
	// Number of satellites for heading ANT
	HsvNum uint8
	// refer to mosaic_h reference page 336.
	AttErr uint8
	// refer to mosaic_h reference page 336.
	AttMode uint8
	// reserved
	Reserved uint8
}

// GetID implements the message.Message interface.
func (*MessageVkMosaichGpsRaw) GetID() uint32 {
	return 53007
}
