//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Weigher state
type MessageVkWeigherState struct {
	// timestamp from system boot
	Timestamp uint32
	// weight in gram
	Weight uint32
	// weight variant rate
	WeightD uint16
	WorkState uint8
	ErrCode uint8
	AttitudeQ [4]float32 `mavext:"true" mavname:"attitude_Q"`
}

// GetID implements the message.Message interface.
func (*MessageVkWeigherState) GetID() uint32 {
	return 53021
}
