//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// EV2 FMU backup status.
type MessageFmubStatus struct {
	// timestamp from systemboot in ms.
	Timestamp uint32
	// euler roll angle.
	Roll float32
	// euler pitch angle.
	Pitch float32
	// euler yaw angle.
	Yaw float32
	// velocity in northward axis.
	Vn float32
	// velocity in eastward axis.
	Ve float32
	// velocity in downward axis.
	Vd float32
	// acceleration in x axis.
	Ax float32
	// acceleration in y axis.
	Ay float32
	// acceleration in z axis.
	Az float32
	// angular velocity in x axis.
	Gx float32
	// angular velocity in y axis.
	Gy float32
	// angular velocity in z axis.
	Gz float32
	// latitude.
	Lat int32
	// longitude.
	Lon int32
	// altitude above mean sea level.
	Amsl float32
	InsStatus int32
	InsFlag int32
	// throttle
	// output.
	Throttle uint16
	// flight mode.
	FlightMode uint8
	// backup
	// takeover
	// status.
	BtakeStatus uint8
}

// GetID implements the message.Message interface.
func (*MessageFmubStatus) GetID() uint32 {
	return 53200
}
