//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// TianQu servo status
type MessageVkflyTianquServoStatus struct {
	Timestamp uint32
	LoadStatus uint32
	ServoStatus uint32
}

// GetID implements the message.Message interface.
func (*MessageVkflyTianquServoStatus) GetID() uint32 {
	return 53030
}
