//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// vkfly gps version
type MessageVkCompVersion struct {
	// component id
	CompId VKFLY_USER_COMP_ID `mavenum:"uint16"`
	// hardware version
	HwVer [16]uint8
	// firmware version
	FwVer [16]uint8
	// SN number
	Sn [16]uint8 `mavname:"SN"`
	// manufactory
	Manufactory [16]uint8
	// model
	Model [16]uint8
	// gnss configuration
	PrivData [16]uint8
}

// GetID implements the message.Message interface.
func (*MessageVkCompVersion) GetID() uint32 {
	return 53006
}
