//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
type MessageVkRoiTarget struct {
	// Timestamp in ms from system boot.
	TimeBootMs uint32
	// wgs48 latitude
	Lat int32
	// wgs48 longitude
	Lon int32
	// altitude amsl, wgs48
	Alt float32
	// Bitmap to indicate ROI state
	State VKFLY_ROI_STATE `mavenum:"uint16"`
}

// GetID implements the message.Message interface.
func (*MessageVkRoiTarget) GetID() uint32 {
	return 53002
}
