//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Mosaic_h gps raw data
type MessageVkFixedwingControlValue struct {
	// Timestamp from system boot.
	Timestamp uint32
	// Roll control value,
	// negative value means roll left.
	RollValue float32
	// Pitch control value,
	// negative value means pitch down.
	PitchValue float32
	// Throttle control
	// value, negative value means throttle off
	ThrottleValue float32
	// Throttle control
	// value, negative value means turn left
	YawValue float32
}

// GetID implements the message.Message interface.
func (*MessageVkFixedwingControlValue) GetID() uint32 {
	return 53009
}
