//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// CACC manager verify message, in json format.
type MessageVkCaccManagerVerify struct {
	// json data length in byte.
	Len uint8
	// json data.
	JsonData [200]uint8
}

// GetID implements the message.Message interface.
func (*MessageVkCaccManagerVerify) GetID() uint32 {
	return 53110
}
