//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// EDU status
type MessageVkflyEduStatus struct {
	// Unix timestamp in ms, from 1 Jan 1970.
	UnixTimestamp uint64
	// Timestamp in ms from system boot.
	BootTimestamp uint32
	// Sequence number for this package.
	Seq uint32
	// Device SN number.
	DevSn uint32
	// 0 for flight controller. 1 for elec-stake
	DevType uint8
	// Retry send this message count.
	RetryCnt uint8
	// 0 no fix, 1 single, 2 RTK
	FixType uint8
	Reserve uint8
	// wgs84 longitude
	Longitude int32
	// wgs84 latitude
	Latitude int32
	// altitude amsl
	Amsl float32
	// altitude above takeoff
	AltRelative float32
	Ve int16
	Vn int16
	Vu int16
	Yaw int16
	Pitch int16
	Roll int16
	YawRate int16
	FlightMode uint8
}

// GetID implements the message.Message interface.
func (*MessageVkflyEduStatus) GetID() uint32 {
	return 53025
}
