//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY udpate acknowledge.
type MessageVkFwUpdateAck struct {
	// Update begin ack.
	Result MAV_RESULT `mavenum:"uint8"`
}

// GetID implements the message.Message interface.
func (*MessageVkFwUpdateAck) GetID() uint32 {
	return 53101
}
