//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// parachute status
type MessageVkParachuteStatus struct {
	// timestamp from system boot
	Timestamp uint32
	// parachute state
	State uint8
	// is auto launch enabled
	AutoLaunch uint8
	// uav command from parachute
	UavCmd uint8
	// parachute error code
	ErrCode uint16
	// parachute backup voltage
	Backvolt float32
}

// GetID implements the message.Message interface.
func (*MessageVkParachuteStatus) GetID() uint32 {
	return 53020
}
