//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
type MessageVkfmuStatus struct {
	// Timestamp in ms from system boot.
	TimeBootMs uint32
	// return to launch reason.
	RtlReason VKFLY_RTL_REASON `mavenum:"uint8"`
	// Loiter reason
	LoiterReason VKFLY_LOITER_REASON `mavenum:"uint8"`
	// fmu sflag3
	SFlag3 uint8
	// ups voltage in 0.1V
	UpsVolt uint16
	// adc voltage in 0.1V
	AdcVolt uint16
	// flight time in seconds
	FlightTime uint32
	// distance to target position in cm
	DistToTar uint32
	// bitmap for servo state
	ServoState uint16
	// flight distance since this power up
	FlightDist float32
	// bitmap for servo state display
	ServoDisplay uint16 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageVkfmuStatus) GetID() uint32 {
	return 53001
}
