//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Mosaic_h gps raw data
type MessageVkDigiEscStatus struct {
	// Index of the first ESC in this message.
	// minValue = 0, maxValue = 60, increment = 4.
	Index uint8
	// Timestamp from system boot.
	Timestamp uint32
	// Reported motor RPM from each ESC (negative for
	// reverse rotation).
	Rpm [4]int32
	// Voltage measured from each ESC.
	Voltage [4]float32
	// Current measured from each ESC.
	Current [4]float32
	// Temperature measured from each ESC.
	Temperature [4]int16
	// Status data from each ESC.
	Status [4]uint32
	// Motro temperature from each ESC.
	MotorTemp [4]int16 `mavext:"true"`
	// Capacity temperature from each ESC.
	CapTemp [4]int16 `mavext:"true"`
	// Status2 data from each ESC.
	Status2 [4]uint32 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageVkDigiEscStatus) GetID() uint32 {
	return 53008
}
