//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY autopilot request update file data from GCS.
type MessageVkFwUpdateDataRequest struct {
	// Offset into the update file.
	Offset uint32
	// Number of bytes.
	Count uint32
}

// GetID implements the message.Message interface.
func (*MessageVkFwUpdateDataRequest) GetID() uint32 {
	return 53102
}
