//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY autopilot update firmware begin. This message send from GCS to autopilot.
type MessageVkFwUpdateBegin struct {
	// Target system id.
	TargetSystem uint8
	// Target compid id.
	TargetComp uint8
	// Size of the firmware file in bytes.
	FileSize uint32
}

// GetID implements the message.Message interface.
func (*MessageVkFwUpdateBegin) GetID() uint32 {
	return 53100
}
