//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// RTK basestaion pvt
type MessageVkRtkBasePvt struct {
	// timestamp from system boot
	Timestamp uint32
	// solved longitude
	Lon int32
	// solved latitude
	Lat int32
	// solved latitude
	Msl float32
	// solved east speed
	Ve float32
	// solved north speed
	Vn float32
	// solved up speed
	Vu float32
	// yaw angle
	Heading float32
	// pitch angle
	Pitch float32
	// position satellite number
	PSatNum uint8
	// heading satellite number
	HSatNum uint8
	// heading satellite number
	PType uint8
	// heading satellite number
	HType uint8
}

// GetID implements the message.Message interface.
func (*MessageVkRtkBasePvt) GetID() uint32 {
	return 53024
}
