//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VK payload message relay
type MessageVkPayloadDataRelay struct {
	// payload address code
	PayloadAddr uint16
	// reserve
	Reserve uint8
	// data field length in bytes
	DataLen uint8
	// data to relay
	Data [128]uint8
}

// GetID implements the message.Message interface.
func (*MessageVkPayloadDataRelay) GetID() uint32 {
	return 53022
}
