//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// battery bms status message
type MessageVkBmsStatus struct {
	// Timestamp in ms from system boot.
	TimeBootMs uint32
	// BMS voltage in mV
	Voltage uint32
	// BMS current in cA, negative value means in
	// charging
	Current int32
	// BMS temperature in degC
	Temperature int16
	// BMS remaining power in percentage
	CapPercent int8
	// BMS id, start from
	// 0
	BatId uint8
	// BMS error code,
	// 0 means no error
	ErrCode uint32
	// BMS cell numbers
	CellNum uint16
	// BMS cell voltage in mV
	CellVolt [30]uint16
	// charge and discharge times
	CycCnt uint16
	// battery healthiness in
	// percentage
	Health uint8
}

// GetID implements the message.Message interface.
func (*MessageVkBmsStatus) GetID() uint32 {
	return 53003
}
