//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
type MessageVkFixedwingRtlCircleWp struct {
	// Latitude in wgs84
	Latitude int32
	// Longitude in wgs84
	Longitude int32
	// Relativ altitude
	Altitude float32
	// Radius in m, NAN means use default radius.
	Radius float32
}

// GetID implements the message.Message interface.
func (*MessageVkFixedwingRtlCircleWp) GetID() uint32 {
	return 53011
}
