//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// Mosaic_h gps raw data
type MessageVkFixedwingServoSignal struct {
	// Timestamp from system boot.
	Timestamp uint32
	// Servo signal
	ServoSignal [16]uint16
}

// GetID implements the message.Message interface.
func (*MessageVkFixedwingServoSignal) GetID() uint32 {
	return 53010
}
