//autogenerated:yes
//nolint:revive,misspell,govet,lll
package vkfly
// VKFLY transfer update terminate. Send this message to terminate a update file
// transfer.
type MessageQingxieBms struct {
	// Battery voltage.
	BatVoltage uint16
	// Servo current.
	ServoCurrent uint16
	// Stack voltage.
	StackVoltage uint16
	// Servo voltage.
	ServoVoltage uint16
	// Battery refuel current.
	BatRefuelCurrent uint16
	// Gas tank pressure.
	GasTankPressure uint16
	// Pipe pressure.
	PipePressure uint16
	// PCB temperature.
	PcbTemp uint16
	// Stack temperature.
	StackTemp uint16
	WorkStatus uint16
	FaltStatus uint16
	SelfCheck uint8
	Id uint8 `mavname:"Id"`
	GassMass uint16 `mavext:"true"`
	GassPercent uint16 `mavext:"true"`
	RuntimeRemain uint16 `mavext:"true"`
	FanPercent uint8 `mavext:"true"`
	FanRpm uint8 `mavext:"true"`
	SysRunState uint8 `mavext:"true"`
	SysFaultState uint8 `mavext:"true"`
	SysFaultCode uint16 `mavext:"true"`
	LipoCurrent uint16 `mavext:"true"`
	TotalRuntime uint16 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageQingxieBms) GetID() uint32 {
	return 53300
}
